### ISSUE TITLE
Access from localhost

### ISSUE THREAD

**Issue by ViktorKeray** [voxic/ha-editor#3]
I have configured the editor with my Home Assistant, but it is fixed to the current system IP. Is there a way to configure the URL to 'localhost', in order to able to run when the system is connected to another network with different IP?

I am referring to this configuration:
```
# Enable the editor panel
panel_iframe:
  editor:
    title: 'Editor'
    url: 'http://xxx.xxx.xxx.xxx:3000' #IP to your home assistant
    icon: mdi:book-open
```
So, practically how to change 'http://xxx.xxx.xxx.xxx:3000' with something like 'http://localhost:3000'? I have already tried with localhost, but unfortunately it doesn't work.
